/*
 * File: test_poisson_fast.c
 * -------------------------
 * Unit test for the Poisson solver (src/poisson_fast.c) and its integration in
 * poisson_solver().
 *
 * Built against test_data/constants.c (ST40-shaped 33 x 65 grid):
 *   cd src && cp ../test_data/constants.c . && make SHOT=0 RUN_NAME=no_mds test_poisson_fast && ./test_poisson_fast
 * checks that initialisation succeeds, that the solution satisfies the stencil
 * given by POISSON_A/B/C and (for these constants) the LIUQE eq. (45) formula
 * from R_VEC, DR and DZ, that it matches a dense LAPACK solve of the same
 * system, and that the shortcut Hagenow flow in poisson_solver() matches a
 * plain two-solve Hagenow flow built on the dense solve.
 *
 * Built with -DEXPECT_INVALID against test_data/constants_poisson_invalid.c
 * (a small grid with a non-finite stencil coefficient):
 *   make SHOT=0 RUN_NAME=no_mds test_poisson_invalid && ./test_poisson_invalid
 * checks that initialisation rejects the stencil and that the solves then
 * return finite zero flux.
 */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cblas.h>
#include <lapacke.h>

#include "constants.h"
#include "gradient.h"
#include "poisson_fast.h"
#include "poisson_solver.h"

#define TOL 1.0e-10

static int n_fail = 0;

#define CHECK(cond, ...)                                             \
    do                                                               \
    {                                                                \
        if (cond)                                                    \
        {                                                            \
            printf("  ok   : " __VA_ARGS__);                         \
        }                                                            \
        else                                                         \
        {                                                            \
            printf("  FAIL : " __VA_ARGS__);                         \
            n_fail++;                                                \
        }                                                            \
        printf("\n");                                                \
    } while (0)

static int is_boundary(int i, int j)
{
    return (i == 0 || i == N_Z - 1 || j == 0 || j == N_R - 1);
}

/* kind 0: smooth source, zero boundary; 1: everything nonzero; 2: all zero. */
static void fill_rhs(int kind, double* b)
{
    for (int i = 0; i < N_Z; i++)
    {
        for (int j = 0; j < N_R; j++)
        {
            const int p = i * N_R + j;
            if (kind == 2)
            {
                b[p] = 0.0;
            }
            else if (kind == 1)
            {
                b[p] = cos(0.37 * (double)p) + 0.1 * sin(1.3 * (double)i) * cos(0.7 * (double)j);
            }
            else
            {
                b[p] = is_boundary(i, j) ? 0.0
                     : sin(3.1 * (double)i / (double)N_Z) * cos(2.3 * (double)j / (double)N_R) + 0.5;
            }
        }
    }
}

#ifndef EXPECT_INVALID
static double rel_dev(const double* x, const double* y, int n)
{
    double max_x = 0.0, max_d = 0.0;
    for (int p = 0; p < n; p++)
    {
        if (fabs(x[p]) > max_x) max_x = fabs(x[p]);
        if (fabs(x[p] - y[p]) > max_d) max_d = fabs(x[p] - y[p]);
    }
    return (max_x > 0.0) ? max_d / max_x : max_d;
}

static int all_finite(const double* x, int n)
{
    for (int p = 0; p < n; p++)
    {
        if (!isfinite(x[p])) return 0;
    }
    return 1;
}
#endif

static int all_zero(const double* x, int n)
{
    for (int p = 0; p < n; p++)
    {
        if (x[p] != 0.0) return 0;
    }
    return 1;
}

#ifndef EXPECT_INVALID
/* Residual of the stencil in constants.c (POISSON_A/B/C) relative to max |b|. */
static double stencil_residual(const double* x, const double* b)
{
    double max_r = 0.0, max_b = 0.0;
    for (int p = 0; p < N_GRID; p++)
    {
        if (fabs(b[p]) > max_b) max_b = fabs(b[p]);
    }
    for (int i = 0; i < N_Z; i++)
    {
        for (int j = 0; j < N_R; j++)
        {
            const int p = i * N_R + j;
            double res;
            if (is_boundary(i, j))
            {
                res = x[p] - b[p];
            }
            else
            {
                res = x[p + N_R] + x[p - N_R] + POISSON_A[j] * x[p + 1] + POISSON_B[j] * x[p - 1]
                    - POISSON_C[j] * x[p] - b[p];
            }
            if (fabs(res) > max_r) max_r = fabs(res);
        }
    }
    return (max_b > 0.0) ? max_r / max_b : max_r;
}

/* Residual of the LIUQE eq. (45) stencil computed from R_VEC, DR and DZ (full
 * cylindrical form, as generated by GSFit for ST40), relative to max |b|. */
static double formula_residual(const double* x, const double* b)
{
    const double k = (DZ / DR) * (DZ / DR);
    double max_r = 0.0, max_b = 0.0;
    for (int p = 0; p < N_GRID; p++)
    {
        if (fabs(b[p]) > max_b) max_b = fabs(b[p]);
    }
    for (int i = 1; i < N_Z - 1; i++)
    {
        for (int j = 1; j < N_R - 1; j++)
        {
            const int p = i * N_R + j;
            const double r = R_VEC[j];
            const double a_j = k * r / (r + DR / 2.0);
            const double b_j = k * r / (r - DR / 2.0);
            const double c_j = 2.0 + a_j + b_j;
            const double res = x[p + N_R] + x[p - N_R] + a_j * x[p + 1] + b_j * x[p - 1] - c_j * x[p] - b[p];
            if (fabs(res) > max_r) max_r = fabs(res);
        }
    }
    return (max_b > 0.0) ? max_r / max_b : max_r;
}

/* Dense reference solve of A x = b with LAPACK (row-major N_GRID x N_GRID). */
static int dense_solve(const double* b, double* x)
{
    double* a = calloc((size_t)N_GRID * (size_t)N_GRID, sizeof(double));
    lapack_int* ipiv = malloc((size_t)N_GRID * sizeof(lapack_int));
    if (a == NULL || ipiv == NULL)
    {
        free(a); free(ipiv);
        return -1;
    }
    for (int i = 0; i < N_Z; i++)
    {
        for (int j = 0; j < N_R; j++)
        {
            const int p = i * N_R + j;
            double* row = &a[(size_t)p * N_GRID];
            if (is_boundary(i, j))
            {
                row[p] = 1.0;
            }
            else
            {
                row[p - N_R] = 1.0;
                row[p + N_R] = 1.0;
                row[p - 1] = POISSON_B[j];
                row[p + 1] = POISSON_A[j];
                row[p] = -POISSON_C[j];
            }
        }
    }
    memcpy(x, b, (size_t)N_GRID * sizeof(double));
    const int info = LAPACKE_dgesv(LAPACK_ROW_MAJOR, N_GRID, 1, a, N_GRID, ipiv, x, 1);
    free(a); free(ipiv);
    return info;
}

/* Plain two-solve Hagenow flow on the dense reference solve. */
static void dense_hagenow(double* b_vec, double* out)
{
    double dpsi_ltrb[N_LTRB];
    double psi_ltrb[N_LTRB];
    dense_solve(b_vec, out);
    gradient_bound(out, dpsi_ltrb);
    for (int ii = 0; ii < N_LTRB; ++ii)
    {
        dpsi_ltrb[ii] = dpsi_ltrb[ii] * INV_R_LTRB_MU0[ii];
    }
    cblas_dgemv(CblasRowMajor, CblasNoTrans, N_LTRB, N_LTRB, 1.0, G_LTRB,
                N_LTRB, dpsi_ltrb, 1, 0.0, psi_ltrb, 1);
    add_bound(psi_ltrb, b_vec);
    dense_solve(b_vec, out);
}
#endif

int main(void)
{
    double* b1 = malloc((size_t)N_GRID * sizeof(double));
    double* b2 = malloc((size_t)N_GRID * sizeof(double));
    double* x1 = malloc((size_t)N_GRID * sizeof(double));
    double* x2 = malloc((size_t)N_GRID * sizeof(double));
#ifdef EXPECT_INVALID
    double psi_ltrb[N_LTRB];
#endif

    const int status = poisson_solver_init();
    printf("grid %d x %d, init status %d, max deviation at init %.3e\n",
           N_R, N_Z, status, poisson_fast_max_deviation());

#ifdef EXPECT_INVALID
    CHECK(status == POISSON_FAST_ERR_COEFFICIENTS, "init rejects the non-finite stencil (status %d)", status);
    CHECK(poisson_fast_status() == POISSON_FAST_ERR_COEFFICIENTS, "status query agrees");
    for (int kind = 0; kind < 3; kind++)
    {
        fill_rhs(kind, b1);
        memcpy(b2, b1, (size_t)N_GRID * sizeof(double));
        poisson_solver(b1, x1);
        CHECK(all_zero(x1, N_GRID) && memcmp(b1, b2, (size_t)N_GRID * sizeof(double)) == 0,
              "poisson_solver() returns zero flux and leaves the source untouched (rhs kind %d)", kind);
        hagenow_bound(b1, x1, psi_ltrb);
        CHECK(all_zero(x1, N_GRID) && all_zero(psi_ltrb, N_LTRB), "hagenow_bound() returns zeros (rhs kind %d)", kind);
    }
#else
    CHECK(status == POISSON_FAST_OK, "init status ok");
    CHECK(poisson_fast_max_deviation() >= 0.0 && poisson_fast_max_deviation() < TOL,
          "init self-check deviation %.3e < %.0e", poisson_fast_max_deviation(), TOL);

    for (int kind = 0; kind < 3; kind++)
    {
        fill_rhs(kind, b1);
        poisson_fast_solve(b1, x2);
        CHECK(all_finite(x2, N_GRID), "solution is finite (rhs kind %d)", kind);
        if (kind == 2)
        {
            CHECK(all_zero(x2, N_GRID), "zero right-hand side gives an exactly zero solution");
            continue;
        }
        const double res = stencil_residual(x2, b1);
        CHECK(res < TOL, "solution satisfies the POISSON_A/B/C stencil (rhs kind %d): %.3e", kind, res);
        const double resf = formula_residual(x2, b1);
        CHECK(resf < TOL, "solution satisfies the LIUQE eq. (45) formula from R_VEC (rhs kind %d): %.3e", kind, resf);
        const int info = dense_solve(b1, x1);
        const double dev = rel_dev(x1, x2, N_GRID);
        CHECK(info == 0 && dev < TOL, "solution matches the dense LAPACK solve (rhs kind %d): %.3e", kind, dev);

        fill_rhs(kind, b1);
        memcpy(b2, b1, (size_t)N_GRID * sizeof(double));
        dense_hagenow(b1, x1);
        poisson_solver(b2, x2);
        const double dev_x = rel_dev(x1, x2, N_GRID);
        const double dev_b = rel_dev(b1, b2, N_GRID);
        CHECK(dev_x < TOL && dev_b < TOL && all_finite(x2, N_GRID),
              "poisson_solver() matches the dense two-solve Hagenow flow (rhs kind %d): flux %.3e, boundary %.3e",
              kind, dev_x, dev_b);
    }

    /* Re-initialisation and lazy initialisation. */
    CHECK(poisson_solver_init() == POISSON_FAST_OK, "re-initialisation succeeds");
    poisson_fast_free();
    CHECK(poisson_fast_status() == POISSON_FAST_NOT_INITIALISED, "poisson_fast_free() resets the status");
    CHECK(poisson_solver_init() == POISSON_FAST_OK, "initialisation after free works");
#endif

    free(b1); free(b2); free(x1); free(x2);
    if (n_fail == 0)
    {
        printf("PASSED\n");
        return 0;
    }
    printf("FAILED: %d check(s)\n", n_fail);
    return 1;
}
