[build-system]
requires = ["setuptools==80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rtgsfit_vs_gsfit"
version = "2025.0.0"
dependencies = [
  "numpy<2",
  "matplotlib",
  "scipy",
  "ipython",
  "jupyter-client",
  "pytest",
  "st40-database",
  "standard-utility",
]
requires-python = ">=3.9"

authors = [
  { name = "Alex Prokopyszyn", email = "alex.prokopyszyn@tokamakenergy.com" }
]
maintainers = [
  { name = "Alex Prokopyszyn", email = "alex.prokopyszyn@tokamakenergy.com" }
]

description = "This repository sets up and runs both GSFIT and RTGSFIT. It uses MDSPlus data only available on Tokamak Energy's network."
readme = "README.md"
license = { text = "GNU GENERAL PUBLIC LICENSE" }
keywords = ["Grad", "Shafranov"]
classifiers = [
  "Programming Language :: Python :: 3"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
