"""
Generate test_data/constants_poisson_invalid.c: a small constants set whose
Poisson stencil contains a non-finite coefficient, so that poisson_solver_init()
must reject it and poisson_solver() must return zero flux.

Only the constants used by poisson_solver.c, poisson_fast.c and gradient.c are
emitted.

Usage (any Python with numpy):
    python test_data/make_constants_poisson_invalid.py
"""
import os

import numpy as np

N_R, N_Z = 9, 11
R_MIN, R_MAX, Z_MIN, Z_MAX = 0.2, 1.0, -0.5, 0.5
MU_0 = 4e-7 * np.pi


def fmt(arr, per_line=8):
    vals = [repr(float(v)) for v in arr]
    lines = [", ".join(vals[i:i + per_line]) for i in range(0, len(vals), per_line)]
    return ",\n    ".join(lines)


def main():
    r_vec = np.linspace(R_MIN, R_MAX, N_R)
    z_vec = np.linspace(Z_MIN, Z_MAX, N_Z)
    dr, dz = r_vec[1] - r_vec[0], z_vec[1] - z_vec[0]
    a = (dz / dr) ** 2 * r_vec / (r_vec + dr / 2)
    b = (dz / dr) ** 2 * r_vec / (r_vec - dr / 2)
    c = 2.0 + a + b
    c[4] = np.nan   # the invalid entry (e.g. a generator dividing by zero)
    n_ltrb = 2 * N_R + 2 * N_Z - 4
    r_ltrb = np.concatenate([r_vec[0] * np.ones(N_Z), r_vec[1:-1], r_vec[-1] * np.ones(N_Z), r_vec[-2:0:-1]])
    z_ltrb = np.concatenate([z_vec, z_vec[-1] * np.ones(N_R - 2), z_vec[::-1], z_vec[0] * np.ones(N_R - 2)])
    assert len(r_ltrb) == n_ltrb
    dist = np.hypot(r_ltrb[:, None] - r_ltrb[None, :], z_ltrb[:, None] - z_ltrb[None, :])
    g_ltrb = 1e-7 * np.log(1.0 + 1.0 / (dist + 0.05))

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "constants_poisson_invalid.c")
    with open(out, "w") as f:
        f.write("/* Generated by test_data/make_constants_poisson_invalid.py. Do not edit.\n"
                " * Small grid whose Poisson stencil has a non-finite coefficient (POISSON_C[4] = nan).\n"
                " * Only the constants needed by the Poisson solver objects are defined. */\n")
        f.write("const int N_Z = %d;\nconst int N_R = %d;\nconst int N_GRID = %d;\nconst int N_LTRB = %d;\n"
                % (N_Z, N_R, N_R * N_Z, n_ltrb))
        f.write("const double DZ = %r;\nconst double DR = %r;\n" % (float(dz), float(dr)))
        f.write("const double R_VEC[] = {\n    %s};\n" % fmt(r_vec))
        f.write("const double Z_VEC[] = {\n    %s};\n" % fmt(z_vec))
        f.write("const double INV_R_LTRB_MU0[] = {\n    %s};\n" % fmt(1.0 / (r_ltrb * MU_0)))
        f.write("const double G_LTRB[] = {\n    %s};\n" % fmt(g_ltrb.flatten()))
        f.write("const double POISSON_A[] = {\n    %s};\n" % fmt(a))
        f.write("const double POISSON_B[] = {\n    %s};\n" % fmt(b))
        f.write("const double POISSON_C[] = {\n    %s};\n" % fmt(c).replace("nan", "__builtin_nan(\"\")"))
    print("wrote", out)


if __name__ == "__main__":
    main()
