"""
Generate test_data/constants_poisson_fallback.c: a small constants set whose
Poisson operator is deliberately NOT separable (the vertical coupling varies
from row to row), so that poisson_fast_init() must reject it and
poisson_solver() must fall back to the banded LU substitution.

Only the constants used by poisson_solver.c, poisson_fast.c, gradient.c and
solve_tria.c are emitted. The LU band extraction follows
tests/rtgsfit_verify_analytic/src/rtgsfit_verify_analytic/poisson_matrix.py.

Usage (any Python with numpy):
    python test_data/make_constants_poisson_fallback.py
"""
import os

import numpy as np

N_R, N_Z = 9, 11
R_MIN, R_MAX, Z_MIN, Z_MAX = 0.2, 1.0, -0.5, 0.5
MU_0 = 4e-7 * np.pi


def operator(r_vec, z_vec):
    n_r, n_z = len(r_vec), len(z_vec)
    dr, dz = r_vec[1] - r_vec[0], z_vec[1] - z_vec[0]
    a = (dz / dr) ** 2 * r_vec / (r_vec + dr / 2)
    b = (dz / dr) ** 2 * r_vec / (r_vec - dr / 2)
    mat = np.zeros((n_r * n_z, n_r * n_z))
    idx = -1
    for i in range(n_z):
        for j in range(n_r):
            idx += 1
            if i == 0 or i == n_z - 1 or j == 0 or j == n_r - 1:
                mat[idx, idx] = 1.0
                continue
            # Vertical coupling that depends on the row: not separable.
            e = 1.0 + 0.2 * np.sin(2.0 * i)
            mat[idx, idx] = -(2.0 * e + a[j] + b[j])
            mat[idx, idx + 1] = a[j]
            mat[idx, idx - 1] = b[j]
            mat[idx, idx + n_r] = e
            mat[idx, idx - n_r] = e
    return mat


def lup_bands(mat, n_r):
    """LU without pivoting (Doolittle), so the banded storage is lossless."""
    n_grid = mat.shape[0]
    upper = mat.astype(np.float64).copy()
    lower = np.eye(n_grid)
    for k in range(n_grid):
        for i in range(k + 1, min(n_grid, k + n_r + 1)):
            if upper[i, k] != 0.0:
                f = upper[i, k] / upper[k, k]
                lower[i, k] = f
                upper[i, k:] -= f * upper[k, k:]
    assert np.allclose(lower @ upper, mat, atol=1e-12)
    lower_pad = np.pad(lower, ((0, 0), (n_r, 0)))
    upper_pad = np.pad(upper, ((0, 0), (0, n_r + 1)))
    lower_band = np.zeros((n_grid, n_r))
    upper_band = np.zeros((n_grid, n_r + 2))
    for ii in range(n_grid):
        lower_band[ii, :] = lower_pad[ii, ii:ii + n_r]
        upper_band[ii, :] = upper_pad[ii, ii:ii + n_r + 2]
    # The banded storage must be lossless for this fixture.
    assert np.allclose(np.tril(lower, -n_r - 1), 0.0)
    assert np.allclose(np.triu(upper, n_r + 2), 0.0)
    upper_band[:, 0] = 1.0 / upper_band[:, 0]
    perm_idx = np.arange(n_grid)
    return perm_idx, lower_band.flatten(), upper_band.flatten()


def fmt(arr, per_line=8, is_int=False):
    vals = [("%d" % v) if is_int else repr(float(v)) for v in arr]
    lines = [", ".join(vals[i:i + per_line]) for i in range(0, len(vals), per_line)]
    return ",\n    ".join(lines)


def main():
    r_vec = np.linspace(R_MIN, R_MAX, N_R)
    z_vec = np.linspace(Z_MIN, Z_MAX, N_Z)
    mat = operator(r_vec, z_vec)
    perm_idx, lower_band, upper_band = lup_bands(mat, N_R)
    n_ltrb = 2 * N_R + 2 * N_Z - 4
    # Boundary traversal (left, top, right, bottom) as in the analytic generator.
    r_ltrb = np.concatenate([r_vec[0] * np.ones(N_Z), r_vec[1:-1], r_vec[-1] * np.ones(N_Z), r_vec[-2:0:-1]])
    z_ltrb = np.concatenate([z_vec, z_vec[-1] * np.ones(N_R - 2), z_vec[::-1], z_vec[0] * np.ones(N_R - 2)])
    assert len(r_ltrb) == n_ltrb
    # A symmetric positive "Green's" matrix stand-in (values are irrelevant for the test).
    dist = np.hypot(r_ltrb[:, None] - r_ltrb[None, :], z_ltrb[:, None] - z_ltrb[None, :])
    g_ltrb = 1e-7 * np.log(1.0 + 1.0 / (dist + 0.05))

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "constants_poisson_fallback.c")
    with open(out, "w") as f:
        f.write("/* Generated by test_data/make_constants_poisson_fallback.py. Do not edit.\n"
                " * Small grid whose Poisson operator is NOT separable (row-dependent vertical coupling).\n"
                " * Only the constants needed by the Poisson solver objects are defined. */\n")
        f.write("const int N_Z = %d;\nconst int N_R = %d;\nconst int N_GRID = %d;\nconst int N_LTRB = %d;\n"
                % (N_Z, N_R, N_R * N_Z, n_ltrb))
        f.write("const double DZ = %r;\nconst double DR = %r;\n" % (float(z_vec[1] - z_vec[0]), float(r_vec[1] - r_vec[0])))
        f.write("const double R_VEC[] = {\n    %s};\n" % fmt(r_vec))
        f.write("const double Z_VEC[] = {\n    %s};\n" % fmt(z_vec))
        f.write("const double INV_R_LTRB_MU0[] = {\n    %s};\n" % fmt(1.0 / (r_ltrb * MU_0)))
        f.write("const double G_LTRB[] = {\n    %s};\n" % fmt(g_ltrb.flatten()))
        f.write("const double LOWER_BAND[] = {\n    %s};\n" % fmt(lower_band))
        f.write("const double UPPER_BAND[] = {\n    %s};\n" % fmt(upper_band))
        f.write("const int PERM_IDX[] = {\n    %s};\n" % fmt(perm_idx, per_line=16, is_int=True))
    print("wrote", out)


if __name__ == "__main__":
    main()
